// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(BookingSystemDbContext))]
    [Migration("20251020084709_FifthMigration_SeedLines")]
    partial class FifthMigration_SeedLines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Bus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("FleetFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FleetFK");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("Domain.Models.Fleet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("YearBuilt")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Fleets");
                });

            modelBuilder.Entity("Domain.Models.Line", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("210776b5-9c0c-4689-94d1-a1de8685ce3b"),
                            Name = "X1A"
                        },
                        new
                        {
                            Id = new Guid("7d6633c4-892c-489a-8698-4b8052286bde"),
                            Name = "TD1"
                        },
                        new
                        {
                            Id = new Guid("cced26d9-1327-4e12-8990-a1829cf64e69"),
                            Name = "TD2"
                        },
                        new
                        {
                            Id = new Guid("102c8597-a47a-40f8-b515-2413305f08f4"),
                            Name = "TD3"
                        },
                        new
                        {
                            Id = new Guid("9301a98e-2b3e-4a0a-9675-c734640ba8e4"),
                            Name = "TD4"
                        },
                        new
                        {
                            Id = new Guid("0fee202a-53bd-442f-aa0c-8be8173ba1fe"),
                            Name = "TD5"
                        },
                        new
                        {
                            Id = new Guid("b78c7b0f-ef06-46fa-9a84-6caba11ead47"),
                            Name = "117"
                        },
                        new
                        {
                            Id = new Guid("67cd380a-60bf-4cac-b1aa-fabf490f4151"),
                            Name = "119"
                        },
                        new
                        {
                            Id = new Guid("71e5774d-5cd5-4362-bf81-2e4ff5d366ef"),
                            Name = "135"
                        },
                        new
                        {
                            Id = new Guid("d140a230-1641-427b-a0ff-0d61fa32f8a6"),
                            Name = "218"
                        },
                        new
                        {
                            Id = new Guid("4a0ad825-7474-4285-a50b-63b3e2c2397d"),
                            Name = "71"
                        },
                        new
                        {
                            Id = new Guid("0a0f4637-6413-46e7-9e1d-c087175ddeaf"),
                            Name = "72"
                        },
                        new
                        {
                            Id = new Guid("fc9d41d8-8c6c-47ec-b747-9c2f101501f6"),
                            Name = "73"
                        },
                        new
                        {
                            Id = new Guid("6de70d79-f4bc-4f11-ae7c-14381f853024"),
                            Name = "201"
                        },
                        new
                        {
                            Id = new Guid("651de373-e20b-4aeb-a9b8-f45f0827a14c"),
                            Name = "208"
                        },
                        new
                        {
                            Id = new Guid("475da1af-e9a8-460b-a10e-86480034bb20"),
                            Name = "214"
                        },
                        new
                        {
                            Id = new Guid("1449c29e-1bd3-4fca-8aed-07bf026692ce"),
                            Name = "N11"
                        },
                        new
                        {
                            Id = new Guid("cb3b0034-ac2a-4f0d-9d08-38704e6bf005"),
                            Name = "N13"
                        },
                        new
                        {
                            Id = new Guid("59586aa6-805c-4621-9c9d-2ffdb746298b"),
                            Name = "N212"
                        },
                        new
                        {
                            Id = new Guid("9fb2ce5d-090c-4f63-b8e7-5634e54f973a"),
                            Name = "N62"
                        },
                        new
                        {
                            Id = new Guid("0381967e-6024-4ae5-937b-e80b92fa7114"),
                            Name = "N82"
                        },
                        new
                        {
                            Id = new Guid("948b2a2f-914a-423f-b067-39916a1b4df4"),
                            Name = "N91"
                        },
                        new
                        {
                            Id = new Guid("338ea7da-45b7-4ac1-912e-3dc7d17e0da6"),
                            Name = "N48"
                        },
                        new
                        {
                            Id = new Guid("d8fcedba-6e54-409e-a280-399624c989eb"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("e6c0c979-8cc9-4710-8005-0abf7a441668"),
                            Name = "2"
                        },
                        new
                        {
                            Id = new Guid("729e8dd4-0ae6-4ca1-8697-b0df167ee8fb"),
                            Name = "3"
                        },
                        new
                        {
                            Id = new Guid("a6125eed-a528-4822-b6f4-5471f61a18ea"),
                            Name = "4"
                        },
                        new
                        {
                            Id = new Guid("0e1e33a6-30bf-4832-a810-8d08eff28492"),
                            Name = "13"
                        },
                        new
                        {
                            Id = new Guid("b00b38f8-313b-486c-b67a-ee741b2af705"),
                            Name = "13A"
                        },
                        new
                        {
                            Id = new Guid("14dc03db-8aac-42d8-978e-e292fcd98d35"),
                            Name = "14"
                        },
                        new
                        {
                            Id = new Guid("72407aa3-340a-4b19-ad1a-ee7820f564b5"),
                            Name = "15"
                        },
                        new
                        {
                            Id = new Guid("ade71bc7-3eff-4643-ba36-a9fd11c7d795"),
                            Name = "16"
                        },
                        new
                        {
                            Id = new Guid("cc311dd0-c80f-4d1f-a373-3a598f8463e2"),
                            Name = "21"
                        },
                        new
                        {
                            Id = new Guid("f71020d3-98b4-40b6-a133-60b9c91231b0"),
                            Name = "22"
                        },
                        new
                        {
                            Id = new Guid("34eecbdb-0e60-4290-816d-0adfea46f7d6"),
                            Name = "24"
                        },
                        new
                        {
                            Id = new Guid("2a062527-a0f6-45bb-9d7d-45133fb8cfdf"),
                            Name = "25"
                        },
                        new
                        {
                            Id = new Guid("4fb76edd-b35e-484f-b0c2-8c2e5a18f663"),
                            Name = "31"
                        },
                        new
                        {
                            Id = new Guid("a03f937a-028d-43db-8d51-e76451f66602"),
                            Name = "32"
                        },
                        new
                        {
                            Id = new Guid("541e3d0f-feff-4575-a02d-0a61928ab468"),
                            Name = "35"
                        },
                        new
                        {
                            Id = new Guid("29712a1e-0e36-4da6-8478-db2141b1ed6f"),
                            Name = "41"
                        },
                        new
                        {
                            Id = new Guid("d9220756-07d4-4980-9783-2b3e88843ec2"),
                            Name = "42"
                        },
                        new
                        {
                            Id = new Guid("ffe88da3-6eef-43d9-b54f-a5129343a3b1"),
                            Name = "43"
                        },
                        new
                        {
                            Id = new Guid("7c28531d-0042-45e0-812c-0579431a8ed8"),
                            Name = "44"
                        },
                        new
                        {
                            Id = new Guid("11b85c06-f927-46c5-98da-9dec751bfd77"),
                            Name = "45"
                        },
                        new
                        {
                            Id = new Guid("97f744c7-b42f-4335-aaa5-934ccc313813"),
                            Name = "46"
                        },
                        new
                        {
                            Id = new Guid("2bd6aa8b-a792-4384-abcb-ffc3c1b5c06c"),
                            Name = "47"
                        },
                        new
                        {
                            Id = new Guid("5b9591c1-a976-44d1-bdb9-278b01b1393a"),
                            Name = "48"
                        },
                        new
                        {
                            Id = new Guid("7228eb45-be81-4dbf-8131-4d82e7dc066d"),
                            Name = "49"
                        },
                        new
                        {
                            Id = new Guid("d5a5266f-622c-4d4c-83fa-31ce2936a1dd"),
                            Name = "50"
                        },
                        new
                        {
                            Id = new Guid("db930adf-141c-43f0-bb90-82b005392390"),
                            Name = "51"
                        },
                        new
                        {
                            Id = new Guid("a217516c-ab23-45a4-bd8b-8cbb0b399d2d"),
                            Name = "52"
                        },
                        new
                        {
                            Id = new Guid("3f9327c2-144c-405f-9b3b-cf90e87444d7"),
                            Name = "53"
                        },
                        new
                        {
                            Id = new Guid("20eba823-5c69-41d4-8051-8afd5d8e2fb1"),
                            Name = "54"
                        },
                        new
                        {
                            Id = new Guid("50a7c2e2-b67a-4312-863f-946c3c9bfc66"),
                            Name = "56"
                        },
                        new
                        {
                            Id = new Guid("6e1cd7c3-29b3-485a-be28-6dc84f1b4425"),
                            Name = "58"
                        },
                        new
                        {
                            Id = new Guid("ac9716c6-accb-4a5f-b78f-e75f9a9fa16b"),
                            Name = "58A"
                        },
                        new
                        {
                            Id = new Guid("23d0d93a-96d7-4327-bae6-7a85064224d1"),
                            Name = "61"
                        },
                        new
                        {
                            Id = new Guid("afb281f7-6972-4b63-88f1-31dc4cdb8225"),
                            Name = "62"
                        },
                        new
                        {
                            Id = new Guid("c779a42f-68f7-465e-a675-22505a744ddf"),
                            Name = "63"
                        },
                        new
                        {
                            Id = new Guid("623cfdd9-26b7-4396-8532-5ec644e121fb"),
                            Name = "64"
                        },
                        new
                        {
                            Id = new Guid("b99477e2-786e-451b-b227-3a05c72d9b7c"),
                            Name = "74"
                        },
                        new
                        {
                            Id = new Guid("fc50fded-11c5-4a97-b8b8-e3ddafc8cc5b"),
                            Name = "80"
                        },
                        new
                        {
                            Id = new Guid("7114fdf6-9289-4b4e-98b5-a891a03373c1"),
                            Name = "81"
                        },
                        new
                        {
                            Id = new Guid("eaeb7317-9f9e-4b7e-8264-be873b3ebd33"),
                            Name = "82"
                        },
                        new
                        {
                            Id = new Guid("4bfa657b-a49d-43ba-9187-054ccf02bd29"),
                            Name = "82A"
                        },
                        new
                        {
                            Id = new Guid("a6728f71-1b74-49d4-a838-31b617b36fa6"),
                            Name = "82B"
                        },
                        new
                        {
                            Id = new Guid("e1d25b79-bb2e-4941-9878-7c7bbbd2e386"),
                            Name = "83"
                        },
                        new
                        {
                            Id = new Guid("73bc18c5-7afd-4b7d-bbe3-8e4190317efb"),
                            Name = "84"
                        },
                        new
                        {
                            Id = new Guid("c8662835-844b-43a1-9654-faeecb88d77d"),
                            Name = "85"
                        },
                        new
                        {
                            Id = new Guid("777f0672-e3a6-4f9a-8c5b-afff690cb12f"),
                            Name = "88"
                        },
                        new
                        {
                            Id = new Guid("0b73af15-4bd6-448c-bab0-e447deacbad4"),
                            Name = "90"
                        },
                        new
                        {
                            Id = new Guid("1e75678a-0df9-4b91-adfc-0ca37c800023"),
                            Name = "91"
                        },
                        new
                        {
                            Id = new Guid("7114b0c2-661a-4f30-a636-97bb340bf2e1"),
                            Name = "92"
                        },
                        new
                        {
                            Id = new Guid("e825c388-e0a6-430f-834c-33d545a75122"),
                            Name = "93"
                        },
                        new
                        {
                            Id = new Guid("b2c40277-e4dd-4ba2-98d6-e7a353336a48"),
                            Name = "94"
                        },
                        new
                        {
                            Id = new Guid("a376d58b-f362-4f71-904d-c789562d4654"),
                            Name = "101"
                        },
                        new
                        {
                            Id = new Guid("401f21eb-b11b-42e7-befa-17dd52c37d76"),
                            Name = "103"
                        },
                        new
                        {
                            Id = new Guid("a5bca6a8-c6d9-483c-a3fc-2e31aac7358c"),
                            Name = "106"
                        },
                        new
                        {
                            Id = new Guid("486f0913-55e2-4153-88e7-c5aa90d11194"),
                            Name = "109"
                        },
                        new
                        {
                            Id = new Guid("aeedf7bb-df5f-4c25-a455-df7a94f2f843"),
                            Name = "109A"
                        },
                        new
                        {
                            Id = new Guid("aa5686d8-3b98-432e-b524-8468a21a2701"),
                            Name = "110"
                        },
                        new
                        {
                            Id = new Guid("95249bf4-139b-4f7b-9a2a-3ddc1ec0ddec"),
                            Name = "120"
                        },
                        new
                        {
                            Id = new Guid("f743cbc2-a4e9-45b1-9a38-5f9b2e030c83"),
                            Name = "121"
                        },
                        new
                        {
                            Id = new Guid("792c4d35-b19d-4ac9-8af9-ba70c6f23659"),
                            Name = "122"
                        },
                        new
                        {
                            Id = new Guid("386a0cb1-1613-4fb8-9268-a02858a3b42e"),
                            Name = "124"
                        },
                        new
                        {
                            Id = new Guid("e22e9dc2-1a77-451b-b2a7-28e34a993c2e"),
                            Name = "130"
                        },
                        new
                        {
                            Id = new Guid("a4a7cfec-2e48-4dcf-a2ba-1720c183b605"),
                            Name = "133"
                        },
                        new
                        {
                            Id = new Guid("1be09fbe-3182-4550-bbe1-a83c7885f7ef"),
                            Name = "181"
                        },
                        new
                        {
                            Id = new Guid("802cc91c-5e88-4227-bb5d-9dc30c378f49"),
                            Name = "182"
                        },
                        new
                        {
                            Id = new Guid("90c9677e-b970-4a8c-964b-513e72dfeb9d"),
                            Name = "186"
                        },
                        new
                        {
                            Id = new Guid("3f86f6a8-1d70-4cea-a8f2-78886e5bb16a"),
                            Name = "202"
                        },
                        new
                        {
                            Id = new Guid("429dc960-8c41-4761-8ace-b892b4517628"),
                            Name = "203"
                        },
                        new
                        {
                            Id = new Guid("c00e1231-b5a2-4ed3-9e47-0dabe8988116"),
                            Name = "204"
                        },
                        new
                        {
                            Id = new Guid("3ac4cf13-4abe-4d74-a97a-a9940d5b9e9f"),
                            Name = "205"
                        },
                        new
                        {
                            Id = new Guid("2dac88e4-0e26-46dd-94a5-66ebd6d4cd18"),
                            Name = "206"
                        },
                        new
                        {
                            Id = new Guid("73d0acf7-bf72-4380-9c62-a674756082fa"),
                            Name = "207"
                        },
                        new
                        {
                            Id = new Guid("7ff7b33b-9e44-47d2-9724-c2e39c695709"),
                            Name = "209"
                        },
                        new
                        {
                            Id = new Guid("357399c1-f7b0-4c41-86df-1bc4ed64e544"),
                            Name = "210"
                        },
                        new
                        {
                            Id = new Guid("398cb0b9-e422-4b4d-b800-1ff702c5335c"),
                            Name = "211"
                        },
                        new
                        {
                            Id = new Guid("80070528-3f8c-4ede-9037-2716d58862c6"),
                            Name = "212"
                        },
                        new
                        {
                            Id = new Guid("356e2493-2dde-40ae-9430-ea7219fe8f34"),
                            Name = "213"
                        },
                        new
                        {
                            Id = new Guid("97ce6239-c5aa-46fc-8570-fc30ad1836d0"),
                            Name = "214"
                        },
                        new
                        {
                            Id = new Guid("602e9b8a-228a-4201-aa65-43db9ff197fe"),
                            Name = "221"
                        },
                        new
                        {
                            Id = new Guid("d5357845-3b14-4a60-9790-933247f846b8"),
                            Name = "222"
                        },
                        new
                        {
                            Id = new Guid("9a973093-092d-4f56-b8c8-55a2271d8e73"),
                            Name = "223"
                        },
                        new
                        {
                            Id = new Guid("e2e56358-1429-49d3-93c2-b33ddb90ea91"),
                            Name = "225"
                        },
                        new
                        {
                            Id = new Guid("dd398fb9-8e1f-46b3-917d-8acf1c85d4f9"),
                            Name = "226"
                        },
                        new
                        {
                            Id = new Guid("7ef06165-fe8c-4f63-b870-a856777c4932"),
                            Name = "233"
                        },
                        new
                        {
                            Id = new Guid("3e1bb8d3-5ba1-489f-9028-a5ab8da76a12"),
                            Name = "238"
                        },
                        new
                        {
                            Id = new Guid("41721a58-3711-4d29-92fc-9dd7cf7b246a"),
                            Name = "250"
                        },
                        new
                        {
                            Id = new Guid("e1b7611f-567e-422b-b080-58750bf091b0"),
                            Name = "260"
                        },
                        new
                        {
                            Id = new Guid("601719e0-048f-4034-b3bb-835df8279873"),
                            Name = "280"
                        },
                        new
                        {
                            Id = new Guid("755aae3e-7062-4716-ac35-9afa59a06f73"),
                            Name = "301"
                        },
                        new
                        {
                            Id = new Guid("60a9f0c4-d827-455a-baf9-b1abaf6d5799"),
                            Name = "302"
                        },
                        new
                        {
                            Id = new Guid("00a24b3a-51f5-43e9-ac97-5807a7f06a10"),
                            Name = "303"
                        },
                        new
                        {
                            Id = new Guid("52799f6f-0118-479d-9da1-eb6664ec8f21"),
                            Name = "305"
                        },
                        new
                        {
                            Id = new Guid("f0346b32-0de2-48dd-86d2-10eede3319c7"),
                            Name = "306"
                        },
                        new
                        {
                            Id = new Guid("734e9822-a316-4502-b9d3-1bb19bc18c3e"),
                            Name = "307"
                        },
                        new
                        {
                            Id = new Guid("8e0c20d2-6df4-47f5-bf52-73e578e59e99"),
                            Name = "308"
                        },
                        new
                        {
                            Id = new Guid("e7c46745-f65c-4950-b40f-a457021d1021"),
                            Name = "309"
                        },
                        new
                        {
                            Id = new Guid("e431da1c-ff29-429e-9c31-e98e05148b87"),
                            Name = "310"
                        },
                        new
                        {
                            Id = new Guid("b89f57c8-2ad1-4a76-9618-edfda60d3a09"),
                            Name = "311"
                        },
                        new
                        {
                            Id = new Guid("04733ce7-e636-4e7e-bbb4-ef69e2d70f16"),
                            Name = "312"
                        },
                        new
                        {
                            Id = new Guid("1fd78c35-5852-4dad-baaa-26a3b9036fa7"),
                            Name = "313"
                        },
                        new
                        {
                            Id = new Guid("94af91b2-f6d8-408c-a5ea-4b2194e685fe"),
                            Name = "322"
                        },
                        new
                        {
                            Id = new Guid("98f1a9f6-146d-4daf-b468-0221594ef710"),
                            Name = "323"
                        },
                        new
                        {
                            Id = new Guid("fd9a9afb-35f1-4793-b60a-cbce8b1abe48"),
                            Name = "330"
                        },
                        new
                        {
                            Id = new Guid("bc0536a4-d39d-44fe-83bc-15a06b0f7938"),
                            Name = "TD10"
                        },
                        new
                        {
                            Id = new Guid("3284fd73-ef3d-4843-8fb9-018a1eee4be7"),
                            Name = "TD13"
                        },
                        new
                        {
                            Id = new Guid("225d071c-0157-4652-b304-19ccf8e25c8e"),
                            Name = "N301"
                        },
                        new
                        {
                            Id = new Guid("daeef622-2929-4447-be40-54b75fe19573"),
                            Name = "X300"
                        },
                        new
                        {
                            Id = new Guid("34245779-4ddb-473e-bd60-7b651bd1ee3b"),
                            Name = "150"
                        },
                        new
                        {
                            Id = new Guid("013ed488-943a-44ae-922b-ac424a298429"),
                            Name = "300"
                        },
                        new
                        {
                            Id = new Guid("3109c832-ea45-42ae-aa05-a7f5dff969cd"),
                            Name = "X299"
                        },
                        new
                        {
                            Id = new Guid("bffd8c4e-c584-467d-938f-df5878d5d41b"),
                            Name = "401"
                        },
                        new
                        {
                            Id = new Guid("d8176cc9-63cf-4a9b-baaa-d6508837cc7e"),
                            Name = "402"
                        },
                        new
                        {
                            Id = new Guid("5c2c6295-4a67-4bdc-b0af-470e87ead3ba"),
                            Name = "403"
                        },
                        new
                        {
                            Id = new Guid("965fe562-a342-4912-a6dc-3ccacf35f170"),
                            Name = "404"
                        },
                        new
                        {
                            Id = new Guid("b5279270-1997-4f25-8111-d02c38d3cf67"),
                            Name = "405"
                        });
                });

            modelBuilder.Entity("Domain.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Domain.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("BusFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LineFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OriginFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TicketTypeFK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BusFK");

                    b.HasIndex("DestinationFK");

                    b.HasIndex("LineFK");

                    b.HasIndex("OriginFK");

                    b.HasIndex("TicketTypeFK");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Domain.Models.TicketType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicketTypes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Bus", b =>
                {
                    b.HasOne("Domain.Models.Fleet", "Fleet")
                        .WithMany()
                        .HasForeignKey("FleetFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("Domain.Models.Ticket", b =>
                {
                    b.HasOne("Domain.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Location", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Location", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.TicketType", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Destination");

                    b.Navigation("Line");

                    b.Navigation("Origin");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
