// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(BookingSystemDbContext))]
    [Migration("20251020114440_SixthMigration_FixedDuplicateEntry")]
    partial class SixthMigration_FixedDuplicateEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Bus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("FleetFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FleetFK");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("Domain.Models.Fleet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("YearBuilt")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Fleets");
                });

            modelBuilder.Entity("Domain.Models.Line", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b05c77a4-3041-4c24-87c0-037da9d85b83"),
                            Name = "X1A"
                        },
                        new
                        {
                            Id = new Guid("08a69000-e7ac-43ea-9cad-1c01b01f1fa7"),
                            Name = "TD1"
                        },
                        new
                        {
                            Id = new Guid("e01e9f74-d7af-46b3-b99d-19a986b1957a"),
                            Name = "TD2"
                        },
                        new
                        {
                            Id = new Guid("87d4f8a6-6dac-46ab-bc07-61d22187ea25"),
                            Name = "TD3"
                        },
                        new
                        {
                            Id = new Guid("a2e2c517-65db-408b-b1d5-7dc1cadca63c"),
                            Name = "TD4"
                        },
                        new
                        {
                            Id = new Guid("538c5f4e-c772-4d26-9ab4-9c91134c7a41"),
                            Name = "TD5"
                        },
                        new
                        {
                            Id = new Guid("4b77f589-0ba4-496b-b1e4-5f11c0e58caf"),
                            Name = "117"
                        },
                        new
                        {
                            Id = new Guid("a15507b8-c707-4c9d-ac1a-70ce72c3d9b7"),
                            Name = "119"
                        },
                        new
                        {
                            Id = new Guid("cf5b7b82-04b9-4f4a-82cd-98f4c0f73948"),
                            Name = "135"
                        },
                        new
                        {
                            Id = new Guid("b7005ea3-aacc-4d86-99fc-e87052017057"),
                            Name = "218"
                        },
                        new
                        {
                            Id = new Guid("7cd6b714-05f7-41c5-a85e-a165033725f0"),
                            Name = "71"
                        },
                        new
                        {
                            Id = new Guid("9ea87a6e-999d-4a01-9086-b24aa1f4b43f"),
                            Name = "72"
                        },
                        new
                        {
                            Id = new Guid("bb466e79-8513-4be3-b69f-44ab16110454"),
                            Name = "73"
                        },
                        new
                        {
                            Id = new Guid("27fdd71d-6cec-4803-8f98-d404d67297a8"),
                            Name = "201"
                        },
                        new
                        {
                            Id = new Guid("c1cc026c-a7cf-4f22-8807-62c358b12533"),
                            Name = "208"
                        },
                        new
                        {
                            Id = new Guid("73d5eb1b-5012-4ae4-83a4-fbce482cde6c"),
                            Name = "214"
                        },
                        new
                        {
                            Id = new Guid("c02cf693-9314-47dc-a372-29b9229f77af"),
                            Name = "N11"
                        },
                        new
                        {
                            Id = new Guid("cfdc7373-c2ee-4cdd-bcf9-61f496f5ea42"),
                            Name = "N13"
                        },
                        new
                        {
                            Id = new Guid("6a5be6bb-5761-45cb-9328-b6053a4b4d00"),
                            Name = "N212"
                        },
                        new
                        {
                            Id = new Guid("606b3342-844a-4d19-9079-3e4c169d2286"),
                            Name = "N62"
                        },
                        new
                        {
                            Id = new Guid("0fdae8ec-e155-4fdd-aef7-b75470ac3090"),
                            Name = "N82"
                        },
                        new
                        {
                            Id = new Guid("ec10ca80-4abf-4f96-9174-a61a80de1461"),
                            Name = "N91"
                        },
                        new
                        {
                            Id = new Guid("feaef86f-5a68-4e00-8d2d-d483504fc4cb"),
                            Name = "N48"
                        },
                        new
                        {
                            Id = new Guid("af6f1b16-580c-48f4-835d-4d50dadcf61f"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("8b94390c-a278-48c1-b9ee-9cb97b5ee893"),
                            Name = "2"
                        },
                        new
                        {
                            Id = new Guid("5f00353a-30c3-4354-ad22-bd183d193478"),
                            Name = "3"
                        },
                        new
                        {
                            Id = new Guid("f5e01b52-2c32-4042-a078-b83e72690605"),
                            Name = "4"
                        },
                        new
                        {
                            Id = new Guid("f2f0ea43-2b37-4b65-a3b6-2e819e35f4d7"),
                            Name = "13"
                        },
                        new
                        {
                            Id = new Guid("d9ddc713-772d-41e9-89ef-d7aa2b0cbd77"),
                            Name = "13A"
                        },
                        new
                        {
                            Id = new Guid("ce390c6d-c5a9-4cb0-a03e-4f59eab45991"),
                            Name = "14"
                        },
                        new
                        {
                            Id = new Guid("7c9b80a8-7cb7-4a82-8cfb-f74e0f9e7bbf"),
                            Name = "15"
                        },
                        new
                        {
                            Id = new Guid("19543a97-93af-4124-a153-d99d8e580283"),
                            Name = "16"
                        },
                        new
                        {
                            Id = new Guid("31fd8be6-fd7c-4d59-8104-4b2e3284e984"),
                            Name = "21"
                        },
                        new
                        {
                            Id = new Guid("00786c36-6323-4465-9729-64c78c9c7dd5"),
                            Name = "22"
                        },
                        new
                        {
                            Id = new Guid("0acac9f3-176a-4191-8415-eafd114f25b9"),
                            Name = "24"
                        },
                        new
                        {
                            Id = new Guid("3757c5b1-8257-4bf5-8c96-8d9c2e378b22"),
                            Name = "25"
                        },
                        new
                        {
                            Id = new Guid("a92ed858-d28d-46b9-bb5f-679597064390"),
                            Name = "31"
                        },
                        new
                        {
                            Id = new Guid("d4b7ab45-92b1-4065-9aa9-c5d42507bb93"),
                            Name = "32"
                        },
                        new
                        {
                            Id = new Guid("068c0dfb-ade9-43d3-89c9-378c02b12458"),
                            Name = "35"
                        },
                        new
                        {
                            Id = new Guid("7b82651c-34f9-4353-b461-be28c875950f"),
                            Name = "41"
                        },
                        new
                        {
                            Id = new Guid("c5e465d1-a9c2-43cc-99af-e4990e26fb57"),
                            Name = "42"
                        },
                        new
                        {
                            Id = new Guid("7fec9cab-979a-447a-a23c-eae6d37e35c3"),
                            Name = "43"
                        },
                        new
                        {
                            Id = new Guid("d9635183-c8d3-498d-b24e-01bd910bf570"),
                            Name = "44"
                        },
                        new
                        {
                            Id = new Guid("b6e34bdb-9e1c-4426-892b-92e72c2a7add"),
                            Name = "45"
                        },
                        new
                        {
                            Id = new Guid("6de9485b-a572-4f87-8152-bb8b06cd29f2"),
                            Name = "46"
                        },
                        new
                        {
                            Id = new Guid("d609fe0b-bc09-479c-a141-aa19ca56b032"),
                            Name = "47"
                        },
                        new
                        {
                            Id = new Guid("1608bec4-5856-4c34-9910-af83da02d0dd"),
                            Name = "48"
                        },
                        new
                        {
                            Id = new Guid("79fe4662-e076-45c5-b462-726b4ef3f08e"),
                            Name = "49"
                        },
                        new
                        {
                            Id = new Guid("b68b721d-3488-43f5-a742-dfe2a7b452f2"),
                            Name = "50"
                        },
                        new
                        {
                            Id = new Guid("65956801-e36c-46b9-b697-89dcab78af12"),
                            Name = "51"
                        },
                        new
                        {
                            Id = new Guid("2e364a29-46a8-44ae-97d8-dd8bb12abd81"),
                            Name = "52"
                        },
                        new
                        {
                            Id = new Guid("89796ffe-5458-4fc0-a806-1ff1484b35d5"),
                            Name = "53"
                        },
                        new
                        {
                            Id = new Guid("d12ab0ef-de7b-4f9a-947a-01fa9bff3a4a"),
                            Name = "54"
                        },
                        new
                        {
                            Id = new Guid("92afa1ef-4883-4ef7-8d84-805a117f0902"),
                            Name = "56"
                        },
                        new
                        {
                            Id = new Guid("9026ea32-83be-4b3a-a09d-4575194b13d3"),
                            Name = "58"
                        },
                        new
                        {
                            Id = new Guid("7e16d41e-5f33-497e-8d52-e796f33badfb"),
                            Name = "58A"
                        },
                        new
                        {
                            Id = new Guid("52269708-4f0d-49a6-9eca-1372017e9d61"),
                            Name = "61"
                        },
                        new
                        {
                            Id = new Guid("91d0c759-7812-4158-9c3e-9230e9f38423"),
                            Name = "62"
                        },
                        new
                        {
                            Id = new Guid("6fd88d1b-5121-4008-85d6-582534b93aaa"),
                            Name = "63"
                        },
                        new
                        {
                            Id = new Guid("190ca961-2ff6-4e7c-8c05-315a9608b079"),
                            Name = "64"
                        },
                        new
                        {
                            Id = new Guid("08187554-5766-4233-b828-6a5a98aca51a"),
                            Name = "74"
                        },
                        new
                        {
                            Id = new Guid("27f31c67-9bb8-4b1c-90bd-2794a74d5718"),
                            Name = "80"
                        },
                        new
                        {
                            Id = new Guid("5987e748-2b04-4b91-99b2-f32adfba3b07"),
                            Name = "81"
                        },
                        new
                        {
                            Id = new Guid("0d65b117-7bfe-4461-9cc4-f75bbc2d81ba"),
                            Name = "82"
                        },
                        new
                        {
                            Id = new Guid("05ef095f-b409-4289-bb66-5a19c79b0e03"),
                            Name = "82A"
                        },
                        new
                        {
                            Id = new Guid("a6193e2e-98fd-4b74-ab41-4484a41a2eb2"),
                            Name = "82B"
                        },
                        new
                        {
                            Id = new Guid("4c8e3608-c79b-4ad1-bc91-88b03efa94db"),
                            Name = "83"
                        },
                        new
                        {
                            Id = new Guid("db5224e0-074f-4b24-99c4-3977e96b23d9"),
                            Name = "84"
                        },
                        new
                        {
                            Id = new Guid("7b7de638-cf9c-4a5f-86b7-47566f6baea0"),
                            Name = "85"
                        },
                        new
                        {
                            Id = new Guid("1271bd41-47fc-44fa-be00-3fa31e2d7676"),
                            Name = "88"
                        },
                        new
                        {
                            Id = new Guid("ba530ce7-d5e4-4d00-a22d-cf78b49cb5ca"),
                            Name = "90"
                        },
                        new
                        {
                            Id = new Guid("66638ac4-85ff-4cc5-a5e4-d5af9b5cf5a7"),
                            Name = "91"
                        },
                        new
                        {
                            Id = new Guid("360b11f4-8256-4cec-af4a-245d4775751c"),
                            Name = "92"
                        },
                        new
                        {
                            Id = new Guid("b3731182-bef0-4097-be82-73c4b8bfdc1e"),
                            Name = "93"
                        },
                        new
                        {
                            Id = new Guid("45f57357-ee05-48b5-88c4-a073e7e5fc2f"),
                            Name = "94"
                        },
                        new
                        {
                            Id = new Guid("d4db81f1-ceb2-4313-863b-872146503efd"),
                            Name = "101"
                        },
                        new
                        {
                            Id = new Guid("c17b4867-16c9-4db2-a15f-239574454aed"),
                            Name = "103"
                        },
                        new
                        {
                            Id = new Guid("1a8b502f-5c9d-43da-8703-3a9d18f308e4"),
                            Name = "106"
                        },
                        new
                        {
                            Id = new Guid("f93d5f22-aeea-40b7-98a5-6f5cbbdb3437"),
                            Name = "109"
                        },
                        new
                        {
                            Id = new Guid("6a822ccb-7095-44d9-ae09-6b68d2b68fca"),
                            Name = "109A"
                        },
                        new
                        {
                            Id = new Guid("3c84dec2-715a-44ba-9d5d-d9749759ca81"),
                            Name = "110"
                        },
                        new
                        {
                            Id = new Guid("20a233ac-cded-4137-bbc7-9f469cae47cd"),
                            Name = "120"
                        },
                        new
                        {
                            Id = new Guid("764ab9da-f84e-4dee-b79e-aaee2debc245"),
                            Name = "121"
                        },
                        new
                        {
                            Id = new Guid("4a1b90da-178b-42ca-a853-51b91bcf756d"),
                            Name = "122"
                        },
                        new
                        {
                            Id = new Guid("6a8d7575-b586-4df0-8146-e9446271ab0d"),
                            Name = "124"
                        },
                        new
                        {
                            Id = new Guid("8c144443-e539-42f4-8085-b14843aefb35"),
                            Name = "130"
                        },
                        new
                        {
                            Id = new Guid("8f2d6ddb-6098-46f4-90cc-c51516629798"),
                            Name = "133"
                        },
                        new
                        {
                            Id = new Guid("f3a58720-ed48-4978-8dcd-584c7263f143"),
                            Name = "181"
                        },
                        new
                        {
                            Id = new Guid("b117050a-d45a-4863-ba06-735ba16d6aa0"),
                            Name = "182"
                        },
                        new
                        {
                            Id = new Guid("ccad766c-dd5d-43f1-a3cf-fe1c616da6c6"),
                            Name = "186"
                        },
                        new
                        {
                            Id = new Guid("bf4bcf4b-3fe5-42d9-8030-1239f3eb4ba3"),
                            Name = "202"
                        },
                        new
                        {
                            Id = new Guid("47f8ec69-a235-409c-8391-dc6b1493f28a"),
                            Name = "203"
                        },
                        new
                        {
                            Id = new Guid("0d2a19fd-1f10-453d-99cc-e730efec8eb5"),
                            Name = "204"
                        },
                        new
                        {
                            Id = new Guid("d7a41001-49cb-41ce-8c77-447529e47233"),
                            Name = "205"
                        },
                        new
                        {
                            Id = new Guid("a27d95df-4d79-42b4-aced-b7dcb949c193"),
                            Name = "206"
                        },
                        new
                        {
                            Id = new Guid("b78be5ca-21b0-4bc0-9888-a600f0a77c21"),
                            Name = "207"
                        },
                        new
                        {
                            Id = new Guid("b3e7f25e-991a-417a-b6fc-58fa1c8bc674"),
                            Name = "209"
                        },
                        new
                        {
                            Id = new Guid("8658f9f1-586b-4771-9232-5ab84e903446"),
                            Name = "210"
                        },
                        new
                        {
                            Id = new Guid("4a22d384-0c88-4137-841d-0e8537240092"),
                            Name = "211"
                        },
                        new
                        {
                            Id = new Guid("dbe56fe6-814b-41a0-8d5e-575784e54d73"),
                            Name = "212"
                        },
                        new
                        {
                            Id = new Guid("ea5aab0f-c17d-4587-89b3-6105044f281d"),
                            Name = "213"
                        },
                        new
                        {
                            Id = new Guid("141ccb78-526e-48c2-9d1e-8143d31fd37d"),
                            Name = "221"
                        },
                        new
                        {
                            Id = new Guid("54296cce-a416-4f00-bbde-7dffcea2ac6d"),
                            Name = "222"
                        },
                        new
                        {
                            Id = new Guid("a8eb2aa9-2a37-410c-a872-0b0dd1343f05"),
                            Name = "223"
                        },
                        new
                        {
                            Id = new Guid("043d3a46-516a-4ba7-bf77-8da3357a4078"),
                            Name = "225"
                        },
                        new
                        {
                            Id = new Guid("a4f6798a-3c3d-4ac6-b195-67c1a1483919"),
                            Name = "226"
                        },
                        new
                        {
                            Id = new Guid("67d041aa-8b42-46c8-b41d-77d428c62310"),
                            Name = "233"
                        },
                        new
                        {
                            Id = new Guid("0ec57979-a7a4-43d1-b9d3-b9076e0338c2"),
                            Name = "238"
                        },
                        new
                        {
                            Id = new Guid("095d438d-2581-42f1-bd46-cc1115fed4e9"),
                            Name = "250"
                        },
                        new
                        {
                            Id = new Guid("0eb05f50-9549-4014-83c0-c82cb211bf61"),
                            Name = "260"
                        },
                        new
                        {
                            Id = new Guid("5e65458e-ef81-4226-98d4-a654b9102edd"),
                            Name = "280"
                        },
                        new
                        {
                            Id = new Guid("32f0a54e-b8f2-499e-8d36-d8c18894169a"),
                            Name = "301"
                        },
                        new
                        {
                            Id = new Guid("80f61972-a8d5-431e-9130-4e63a98295df"),
                            Name = "302"
                        },
                        new
                        {
                            Id = new Guid("aedac7a0-75b0-49bb-8c10-8b7d12dba1c3"),
                            Name = "303"
                        },
                        new
                        {
                            Id = new Guid("1f4b6fe7-f835-4ad7-b9ea-af9d3badd5e1"),
                            Name = "305"
                        },
                        new
                        {
                            Id = new Guid("69232e18-fee8-48c9-8a23-9e118d0dd846"),
                            Name = "306"
                        },
                        new
                        {
                            Id = new Guid("25bd5836-52ae-492a-9362-63e916f37ff2"),
                            Name = "307"
                        },
                        new
                        {
                            Id = new Guid("1c60af9e-1b1c-4251-8086-e78bc19bcd76"),
                            Name = "308"
                        },
                        new
                        {
                            Id = new Guid("bc64dfea-08d6-4e54-9c0b-844427292bdf"),
                            Name = "309"
                        },
                        new
                        {
                            Id = new Guid("85e9d124-fa53-4f24-b02e-af8328d99bc6"),
                            Name = "310"
                        },
                        new
                        {
                            Id = new Guid("083e494b-1c43-4f8c-894e-d4e94d1281a2"),
                            Name = "311"
                        },
                        new
                        {
                            Id = new Guid("504b5233-2fd3-4e80-8b58-df655eca489f"),
                            Name = "312"
                        },
                        new
                        {
                            Id = new Guid("9a0353c1-e539-4357-9543-e5de1a4af996"),
                            Name = "313"
                        },
                        new
                        {
                            Id = new Guid("9281c2ae-41b4-4add-aee0-a1630212f73f"),
                            Name = "322"
                        },
                        new
                        {
                            Id = new Guid("eb7a75c5-31bd-44bb-9a78-02cccc1ca8a2"),
                            Name = "323"
                        },
                        new
                        {
                            Id = new Guid("17f4fb38-95e3-4b52-ac2b-240caa9f0f9b"),
                            Name = "330"
                        },
                        new
                        {
                            Id = new Guid("0613fd73-50b6-4459-be9c-3f0f15404029"),
                            Name = "TD10"
                        },
                        new
                        {
                            Id = new Guid("d37cfc4f-3f76-4cdf-bbc6-a6c203fb3620"),
                            Name = "TD13"
                        },
                        new
                        {
                            Id = new Guid("f63dc236-1f02-46e9-a30a-cc057b1b438c"),
                            Name = "N301"
                        },
                        new
                        {
                            Id = new Guid("7ec27ac4-2058-4368-b566-675ead63b84b"),
                            Name = "X300"
                        },
                        new
                        {
                            Id = new Guid("39beda93-527c-411c-8fdc-1b5c46938945"),
                            Name = "150"
                        },
                        new
                        {
                            Id = new Guid("9dc753ae-49c6-4fe5-88d8-c9b5343f149c"),
                            Name = "300"
                        },
                        new
                        {
                            Id = new Guid("ba598d8a-7c41-4e45-98d8-aa44a3efab34"),
                            Name = "X299"
                        },
                        new
                        {
                            Id = new Guid("271eaaf6-0d89-4e25-a7e6-8fd8b6adc813"),
                            Name = "401"
                        },
                        new
                        {
                            Id = new Guid("247cb73c-0152-4245-a0ae-e8ba019585ab"),
                            Name = "402"
                        },
                        new
                        {
                            Id = new Guid("729afcf0-ad1a-4ac4-aad6-71be0a261550"),
                            Name = "403"
                        },
                        new
                        {
                            Id = new Guid("32928679-9eec-4268-b243-495bc6982055"),
                            Name = "404"
                        },
                        new
                        {
                            Id = new Guid("c7f1cb3c-8392-4d93-bbf8-a8de45df559b"),
                            Name = "405"
                        });
                });

            modelBuilder.Entity("Domain.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Domain.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("BusFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LineFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OriginFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TicketTypeFK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BusFK");

                    b.HasIndex("DestinationFK");

                    b.HasIndex("LineFK");

                    b.HasIndex("OriginFK");

                    b.HasIndex("TicketTypeFK");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Domain.Models.TicketType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicketTypes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Bus", b =>
                {
                    b.HasOne("Domain.Models.Fleet", "Fleet")
                        .WithMany()
                        .HasForeignKey("FleetFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("Domain.Models.Ticket", b =>
                {
                    b.HasOne("Domain.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Location", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Location", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.TicketType", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Destination");

                    b.Navigation("Line");

                    b.Navigation("Origin");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
